runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: 24.10.0
    - run: node --version
      shell: bash
    - run: yarn --version
      shell: bash
    - run: yarn install --immutable --immutable-cache
      shell: bash
