compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  '@octokit/plugin-retry@*':
    dependencies:
      '@octokit/request-error': '*'
  babel-plugin-transform-async-to-promises@*:
    dependencies:
      '@babel/core': '*'

yarnPath: .yarn/releases/yarn-4.10.3.cjs
