packages:
  - packages/*

catalog:
  "@changesets/changelog-github": ^0.7.0
  "@changesets/cli": ^2.31.0
  "@effect/language-service": ^0.86.2
  "@effect/platform-node": 4.0.0-beta.83
  "@effect/vitest": 4.0.0-beta.83
  "@fast-check/vitest": ^0.4.1
  "@types/node": ^22.19.19
  dprint: ^0.54.0
  effect: 4.0.0-beta.83
  oxc-parser: 0.135.0
  oxlint: ^1.66.0
  typescript: ^6.0.3
  vitest: 4.1.7

catalogMode: strict

peerDependencyRules:
  allowedVersions:
    "@effect/vitest>vitest": "4"
