import type { SymbolaMethod } from "./symbola.types.ts";

const generatedHeader = `// Generated by packages/effect-codegen/src/GenerateSupportedPairs.ts.
// Run \`pnpm --filter @symbola/effect-codegen codegen\` to update.
`;

export function renderSupportedPairs(methods: readonly SymbolaMethod[]): string {
  const sortedPairs = [...methods].toSorted(compareMethod);
  return `${generatedHeader}
export type DirectFix = {
  readonly kind: "receiverFirst";
};

export type PipeFix = {
  readonly kind: "pipeOperator";
};

export type SymbolaPair = {
  readonly module: string;
  readonly direct: DirectFix | false;
  readonly method: string;
  readonly pipe: PipeFix | false;
  readonly symbol: string;
};

const receiverFirst = { kind: "receiverFirst" } as const satisfies DirectFix;
const pipeOperator = { kind: "pipeOperator" } as const satisfies PipeFix;

export const supportedPairs = [
${renderPairGroups(sortedPairs)}
] as const satisfies readonly SymbolaPair[];

export const supportedPairsByModule = new Map<string, ReadonlyMap<string, SymbolaPair>>(
  Object.entries(
    supportedPairs.reduce<Record<string, Record<string, SymbolaPair>>>((modules, pair) => {
      modules[pair.module] ??= {};
      modules[pair.module][pair.method] = pair;
      return modules;
    }, {}),
  ).map(([module, pairs]) => [module, new Map(Object.entries(pairs))]),
);
`;
}

function compareMethod(left: SymbolaMethod, right: SymbolaMethod): number {
  return (
    left.effectModule.localeCompare(right.effectModule) ||
    left.effectMethod.localeCompare(right.effectMethod) ||
    left.symbol.localeCompare(right.symbol)
  );
}

function renderPairGroups(methods: readonly SymbolaMethod[]): string {
  const groups = new Map<string, SymbolaMethod[]>();
  for (const method of methods) {
    const group = groups.get(method.effectModule);
    if (group === undefined) {
      groups.set(method.effectModule, [method]);
    } else {
      group.push(method);
    }
  }
  return [...groups]
    .map(
      ([moduleSpecifier, modulePairs]) =>
        `  // ${moduleSpecifier}\n${modulePairs.map(renderPair).join("\n")}`,
    )
    .join("\n");
}

function renderPair(method: SymbolaMethod): string {
  return `  {
    module: ${JSON.stringify(method.effectModule)},
    direct: ${fixReference(method.direct)},
    method: ${JSON.stringify(method.effectMethod)},
    pipe: ${fixReference(method.pipe)},
    symbol: ${JSON.stringify(method.symbol)},
  },`;
}

function fixReference(fix: SymbolaMethod["direct"]): string {
  return fix === false ? "false" : fix.kind;
}
