export { default as Composable, compose } from './Composable'
export { default as Memoizable, memoize } from './Memoizable'
export { default as Onceable, once } from './Onceable'
export { default as Flippable, flip } from './Flippable'
export { default as Curryable, _curry } from './Curryable'
export { default as Catchable, _catch } from './Catchable'
