import type { SymbolaMethod } from "../supportedPairs/symbola.types.ts";

const supportedArrayMethods = new Set(["filter", "flatMap", "map"]);

export function renderArrayRuntime(methods: readonly SymbolaMethod[]): string {
  if (supportedArrayRuntimeMethods(methods).length === 0) {
    throw new Error("No supported Array runtime methods were generated");
  }

  return `// Generated by packages/effect-codegen/src/GenerateSupportedPairs.ts.
// Run \`pnpm --filter @symbola/effect-codegen codegen\` to update.

import * as EffectArray from "effect/Array"
import * as Effect from "effect/Effect"

import { filter, flatMap, map } from "../../Symbols.ts"
import { install } from "../install.ts"

export { filter, flatMap, map } from "../../Symbols.ts"

declare global {
  interface ReadonlyArray<T> extends ArrayProtocol<T> {}
}

abstract class ArrayProtocol<A> {
  [map]<B>(this: readonly A[], f: (value: A, index: number) => B): readonly B[] {
    return EffectArray.map(this, f)
  }

  [filter]<B extends A>(
    this: readonly A[],
    predicate: (value: A, index: number) => value is B
  ): readonly B[]
  [filter](this: readonly A[], predicate: (value: A, index: number) => boolean): readonly A[]
  [filter](this: readonly A[], predicate: (value: A, index: number) => boolean): readonly A[] {
    return EffectArray.filter(this, predicate)
  }

  [flatMap]<B>(this: readonly A[], f: (value: A, index: number) => readonly B[]): readonly B[] {
    return EffectArray.flatMap(this, f)
  }
}

Effect.runSync(install(ArrayProtocol.prototype, Array.prototype))
`;
}

export function arrayRuntimePairKeys(
  methods: readonly SymbolaMethod[],
): ReadonlySet<string> {
  return new Set(
    supportedArrayRuntimeMethods(methods).map(
      (method) => `${method.effectModule}:${method.symbol}`,
    ),
  );
}

function supportedArrayRuntimeMethods(
  methods: readonly SymbolaMethod[],
): readonly SymbolaMethod[] {
  return methods.filter(
    (method) =>
      method.effectModule === "effect/Array" &&
      supportedArrayMethods.has(method.symbol),
  );
}
