name: CI/CD

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - core
          - function
          - number
          - object
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Build
        run: yarn build

      - name: Jest
        run: yarn p:${{ matrix.package }} test:ci

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: packages/${{ matrix.package }}/coverage/lcov.info
          flag-name: smybola-${{ matrix.package }}
          parallel: true

  finish:
    name: Coverage
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: ESLint
        run: yarn lint:eslint

      - name: Prettier
        run: yarn lint:prettier

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Build
        run: yarn build:prod

      - name: Release
        run: yarn multi-semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  docs:
    name: Docs
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Build
        run: yarn build

      - name: Generate
        run: yarn docs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
